### ISSUE TITLE
Ch 4 - Redesign Online DFS Agent diagram

### ISSUE THREAD

**Issue by redblobgames** [aimacode/aima-javascript#116]
The [existing diagram](http://aimacode.github.io/aima-javascript/4-Beyond-Classical-Search/#online-dfs-agent) is an implementation of the algorithm but we want diagrams that show the concepts and how the algorithm works. For example, the diagram should show untried and unbacktracked from the algorithm.

**Comment by kaushikgunda** [comment]
@redblobgames Hey, i wish to work on this.I want to propose a few representations and ask for improvements.
1. In the same grid, at every current state changing the colors of the surrounding cells based on whether they are unbacktracked or not and also showing arrows for the all the directions of untried.
2. Showing three grids, one for actual movement, one for the untried and one for the unbacktracked.

Apart from these i also propose to add a few more things like 
1.pausing
2.going back to previous state 
3.Initial state and goal given by the user.
4.Cost function calculation.
so that anyone who is looking at the simulation can understand whether it is truly online dfs or not.

Can you  please suggest me improvements  so that i can start working on it.
P.S:- I am very new to designing but i look forward to learn it by contributing and brainstorming in a more known field i.e AI.

**Comment by redblobgames** [comment]
@kaushikgunda If you are interested in GSoC 2018, then be sure to read https://github.com/aimacode/aima-gsoc and contact the mentor. If you are NOT interested in GSoC, then yes, feel free to work on this issue, but I am no longer on this project so you may have to wait until there are new people who start working on it.
