### ISSUE TITLE
Chapter Navigation

### ISSUE THREAD

**Issue by Dragneel7** [aimacode/aima-javascript#135]
When we click on a link either in header or index page it leads the reader to the specified folder. Would it not be more reasonable to navigate the reader directly to index.html in that respective folder.
![deepinscreenshot_20171227094657](https://user-images.githubusercontent.com/24193342/34370602-4c8f3df4-eaeb-11e7-9fa9-b09a42b1f440.png)

**Comment by redblobgames** [comment]
Because browsers do not allow some features over file:/// URLs, many of the diagrams do not work with file:/// URLs anyway. So it may not help much to change this. You will need to run a local webserver (see [the wiki](https://github.com/aimacode/aima-javascript/wiki/Building) for a python command to start the local webserver). The file:/// URLs are for debugging only, and when debugging it is sometimes useful to be able to see the folder contents. But I do not have a strong opinion on this; it is probably best for the next GSoC student/mentor to decide which way works best for them.
