### ISSUE TITLE
Chapter 5 - Tic Tac Toe - The Computer loses.

### ISSUE THREAD

**Issue by soham23** [aimacode/aima-javascript#168]
The page says the computer won't get anything worse than a draw. It does, though.
It doesn't display "O wins" instead, it displays "Draw".

![screenshot 15](https://user-images.githubusercontent.com/16370482/48658445-b9878e80-ea67-11e8-9a91-56615a3a2ffa.png)

**Comment by AnimeshSinha1309** [comment]
Yeah, Replicated the result, O(2,2) - X(3,3) - O(1,1) - X(2,3) - O (1,3) - **The Computer Lost, Two threats it cannot deal with** - X(1,2) - O(3,1), *The Human Wins, but the computer says draw*.

I guess this is an issue with the evaluation function, will try to solve the issue.

**Comment by GaurangTandon** [comment]
Seems the file is @AnimeshSinha1309 

https://github.com/aimacode/aima-javascript/blob/master/5-Adversarial-Search/draw.js#L123

It seems `board.gameState` is never being set to `1`.

**Comment by AnimeshSinha1309** [comment]
I don't think we should do this, I agree that that would fix the issue that I says game draw. But then that should never be possible if the reset of the decision tree is working.

**Comment by GaurangTandon** [comment]
Yes, the fix is only intended to be temporary, until the decision tree is back up again.

**Comment by AnimeshSinha1309** [comment]
I pulled apart the value for each node, and it turns out that it is failing for the terminal states, that is when a side won. Here, there is no call to `this.board.value`, so if the game is won by a side, and the node is a leaf node, the output gets governed by
https://github.com/aimacode/aima-javascript/blob/3cf3bae09563fc19f49d02a878e037e6866ac566/5-Adversarial-Search/tree.js#L131
Which initializes the best value to +infinity or -infinity based on whose turn it is, not on **who already won**.

Function causing the error here:
https://github.com/aimacode/aima-javascript/blob/3cf3bae09563fc19f49d02a878e037e6866ac566/5-Adversarial-Search/tree.js#L127-L147

**Comment by AnimeshSinha1309** [comment]
Sorry, the previous hunch seems wrong. The tree when constructed fixes its leaf node and assigns then the apt values, so its not needed again. But the lines of code that are breaking it are:
https://github.com/aimacode/aima-javascript/blob/3cf3bae09563fc19f49d02a878e037e6866ac566/5-Adversarial-Search/tree.js#L142-L144.
Should this not be:
```javascript
if (this.board.turn == 1 && this._value >= beta) return this._value; // Human - Maximizing Agent
if (this.board.turn != 1 && this._value <= alpha) return this._value; // Computer - Minimizing Agent
```
In any case, removing the alpha-beta pruning segment makes the whole thing work.

**Comment by AnimeshSinha1309** [comment]
I have put together a solution. It works perfectly, please review and tell me if you can still beat the computer.

**Comment by soham23** [comment]
Nope, I couldn't find a way to beat this one:
https://github.com/AnimeshSinha1309/AimaJavascript/tree/master/5-Adversarial-Search
